fix AWS ELB max 20 issue
rancher/external-lb pull request #22
Opened 2017-09-18 09:18 UTC by loganhz

[issue rancher/rancher#7307](https://github.com/rancher/rancher/issues/7307)

2017-09-18 09:20 UTC, loganhz commented
@yasker fixed. Need a QA to test it.
thanks a lot

2017-10-05 15:09 UTC, brooksgarrett commented
Any chance of this getting merged?

2017-10-05 17:15 UTC, yasker commented
@brooksgarrett We're waiting for QA to test. In the meantime, you can also try it and let us know. @loganhz has instructions at https://github.com/rancher/rancher/issues/7307

2017-10-05 18:10 UTC, brooksgarrett commented
@yasker Thanks for the update. I pulled the patch submitted by @loganhz this morning and built a container for our private repo. It resolved the issue immediately and I have not yet noticed any errors or issues. I'll post back if anything comes up but so far it is looking good on my end!

Thanks for all you guys (and girls) do!

2017-10-05 18:18 UTC, yasker commented
@brooksgarrett Glad it helps! Feel free to let us know if any issue pops up. As I said, we will merge it after it passed our QA test, which should happen soon.

2017-10-06 02:37 UTC, yasker requested changes

2017-10-06 02:37 UTC, yasker commented on providers/elbv1/elbv1svc/elb_classic.go
> +		tagDescriptions = append(tagDescriptions, resp.TagDescriptions...)
Keep the `err` statement following the assignment, otherwise you're risking a NPE.

2017-10-06 02:48 UTC, loganhz commented
@yasker done

2017-10-06 03:04 UTC, yasker approved these changes

2017-10-06 03:04 UTC, yasker commented
LGTM.

2017-10-06 04:58 UTC, alena1108 commented
LGTM

2017-10-06 04:58 UTC, merged